### ISSUE TITLE
run_XBNE import error

### ISSUE THREAD

**Issue by sarathsurpur** [tusharsarkar3/XBNet#1]
I tried to run this package on colab facing the below error, when I try to import the run_XBNE

from XBNet.run import run_XBNE

ImportError: cannot import name 'run_XBNE' from 'XBNet.run' (/usr/local/lib/python3.7/dist-packages/XBNet/run.py)

**Comment by tusharsarkar3** [comment]
It's run_XBNET and not run run_XBNE.
