### ISSUE TITLE
Please update eval_metric from 'merror' to 'mlogloss'

### ISSUE THREAD

**Issue by GDGauravDutta** [tusharsarkar3/XBNet#6]
Please update eval_metric from 'merror' to 'mlogloss'

WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

**Comment by tusharsarkar3** [comment]
Done
